pipeline {
    agent {
        dockerfile {
            dir '.ci'
            label 'docker-executor'
        }
    }

    options {
        withAWS(endpointUrl: 'https://storage.kevinlin.info', credentials: 'storage-internal')
    }

    stages {
        stage('Install') {
            steps {
                sh 'go get -d ./...'
                sh 'make dependencies'
            }
        }
        stage('Lint') {
            steps {
               sh 'make lint'
            }
        }
        stage('Build') {
            parallel {
                stage('linux/amd64') {
                    environment {
                        GOOS = 'linux'
                        GOARCH = 'amd64'
                    }
                    steps {
                        sh 'make'
                    }
                }
                stage('linux/arm') {
                    environment {
                        GOOS = 'linux'
                        GOARCH = 'arm'
                    }
                    steps {
                        sh 'make'
                    }
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: 'bin/*', fingerprint: true
        }
    }
}
